Repository Abishethvarman/HNDIT3032-Data-Structures-and-Algorithms, pull requests merged in 2024-10, with the labels that each got.

#1 Create readme.md
  4-LinkedList/readme.md
Labels: hacktoberfest

#2 Create readme.md
  5-Vector/readme.md
Labels: hacktoberfest-accepted

#3 Create DSA_Array.java
  2-Array/DSA_Array.java
Labels: hacktoberfest-accepted

#4 Create DSA_Vector.java
  5-Vector/DSA_Vector.java
Labels: hacktoberfest, hacktoberfest-accepted

#5 index-1-bigo-answers
  1-bigO/students_answers/indexno-1-bigo-answers.md
Labels: hacktoberfest, hacktoberfest-accepted
